### PR TITLE
Update to .net 8.0; Add Basic Auth; Works with v20U2

### PR DESCRIPTION
**Pull request by bk-lg**
I added the quickfix from #26. 
I also implemented a basic auth implementation.
I normaly don't write code so please validate the implementation before relying on it at all.

### CODE REVIEW

**Review by Labfox — APPROVED** [review]
Looks good

**Comment by bk-lg** [comment]
I plan to upgrade my fork to .net 8 für v20 of 3cx in the next weeks or months. I'll update the merge requests after I succeeded. 
This is a low prio topic for me at work in the moment so I can't promise anything and I am still no developer so will be a dedicated code review of anyone who want to use this strongly advised.

**Comment by bk-lg** [comment]
@Montesuma80 @ic32k i updated an tested my changes with the current v20 release and and it works as before.
I would be happy if you can find some time to look into the pull request.

**Comment by bk-lg** [comment]
@Montesuma80 thanks for looking into it!

**Pull request merged**
